config/routes.rb
Rails.application.routes.draw do
  
  resources :epd_indicators
  resources :epds
  resources :mk_puntuacions
  resources :mk_imatges
  resources :mk_documents
  resources :mk_users
  get 'marketcons/index'
  get 'marketcons', to: 'marketcons#index', as: :marketcons
  get 'marketcons/about'
  get 'marketcons/producte'
  get 'marketcons/perfil'
  get 'marketcons/venedor'
  get 'marketcons/nou_anunci'
  get 'marketcons/editar_anunci'
  get 'marketcons/comprova_unitats_categoria'
  get 'marketcons/categoria'
  get 'marketcons/missatges'
  get 'marketcons/aprovacions'
  get 'marketcons/publicats'
  get 'marketcons/usuaris'
  get 'marketcons/reserva_producte'
  get 'marketcons/anula_reserva_producte'
  get 'marketcons/producte_venut'
  get 'marketcons/producte_amagar'

  get 'mobile_marketcons/index'
  get 'mobile_marketcons', to: redirect('mobile_marketcons/index?distancia=tots&preu=tots&categoria=tots'), as: :mobile_marketcons
  get 'mobile_marketcons/about'
  get 'mobile_marketcons/producte'
  get 'mobile_marketcons/perfil'
  get 'mobile_marketcons/venedor'
  get 'mobile_marketcons/puntua_usuari'
  get 'mobile_marketcons/grava_puntuacio_usuari'
  get 'mobile_marketcons/nou_anunci'
  get 'mobile_marketcons/editar_anunci'
  get 'mobile_marketcons/comprova_unitats_categoria'
  get 'mobile_marketcons/categoria'
  get 'mobile_marketcons/missatges'
  get 'mobile_marketcons/aprovacions'
  get 'mobile_marketcons/publicats'
  get 'mobile_marketcons/usuari'
  get 'mobile_marketcons/usuaris'
  get 'mobile_marketcons/reserva_producte'
  get 'mobile_marketcons/anula_reserva_producte'
  get 'mobile_marketcons/producte_venut'
  get 'mobile_marketcons/producte_amagar'
  get 'mobile_marketcons/idioma'

  get 'mk_products/aprovar'
  get 'mk_products/desaprovar'
  resources :mk_categories
  resources :mk_missatges
  resources :mk_products
  resources :document_dapcons
  resources :organitzacio_afiliades
  get 'cas_practics/llistat'
  resources :cas_practics
  resources :indicador_usuaris
  resources :producte_dapcons_usuaris
  resources :indicadors
  resources :tipus_dada_inventaris
  resources :tipus_indicadors
  resources :producte_dapcons
  get 'dapcons', to: 'dapcons#index', :as => :dapcons
  get 'dapcons/index'
  get 'dapcons/que_son'
  get 'dapcons/utilitat'
  get 'dapcons/organitzacions_afiliades'
  get 'dapcons/productes_registrats'
  get 'dapcons/empreses_dapcons'
  get 'dapcons/documents_oficials'
  get 'dapcons/administradors'
  get 'dapcons/consell_assessor'
  get 'dapcons/panells_sectorials'
  get 'dapcons/eco_platform'
  get 'dapcons/entitats_colaboradores'
  get 'dapcons/verificadors'
  get 'dapcons/afiliacio'
  get 'dapcons/registrar_producte'
  get 'dapcons/contacte'
  get 'dapcons/comparador'
  get 'dapcons/llistat_productes'
  resources :videos
  get 'noticies/llistat'
  resources :noticies
  resources :empreses
  resources :categories
  resources :categoria_productes
  resources :ecoetiqueta_productes
  resources :ecoetiquetes
  resources :document_productes
  resources :productes
  devise_for :users
  
  get 'temes_clau/index'
  get 'temes_clau/marc_conceptual'
  get 'temes_clau/materials'
  get 'temes_clau/energia_passius'
  get 'temes_clau/energia_actius'
  get 'temes_clau/energia_renovables'
  get 'temes_clau/aigua'
  get 'temes_clau/residus'
  get 'temes_clau/salut'
  get 'temes_clau/economia_circular'
  get 'temes_clau/infraestructura_verda'


  get 'cas_practics/:cas_practics_id/edit_ca', to: 'cas_practics#edit_ca', :as => :cas_practics_edit_ca
  get 'cas_practics/:cas_practics_id/edit_es', to: 'cas_practics#edit_es', :as => :cas_practics_edit_es
  get 'cas_practics/:cas_practics_id/edit_en', to: 'cas_practics#edit_en', :as => :cas_practics_edit_en


  get 'home/index'
  get 'home/panel'
  get 'home/quisom'
  get 'home/avislegal'
  get 'home/cookies'
  get 'home/contacta'
  get 'home/logout'

  get 'index.php/ca/sistema_dapc/*other', to: redirect('dapcons/index?locale=ca')
  get 'index.php/es/sistema_dapc/*other', to: redirect('dapcons/index?locale=es')
  get 'index.php/ca/*other', to: redirect('home/index?locale=ca')
  get 'index.php/es/*other', to: redirect('home/index?locale=es')

  get 'interaccions', to: 'interaccions#create', as: :interaccions
  get 'interaccions/descarregues_dapcons', to: 'interaccions#descarregues_dapcons'
  
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mk_user.rb
class MkUser < ApplicationRecord

	has_one_attached :mk_image_user
	belongs_to :user

end

app/controllers/mk_users_controller.rb
class MkUsersController < ApplicationController
  before_action :set_mk_user, only: [:show, :edit, :update, :destroy]

  # GET /mk_users
  # GET /mk_users.json
  def index
    @mk_users = MkUser.all
  end

  # GET /mk_users/1
  # GET /mk_users/1.json
  def show
  end

  # GET /mk_users/new
  def new
    @mk_user = MkUser.new
  end

  # GET /mk_users/1/edit
  def edit
  end

  # POST /mk_users
  # POST /mk_users.json
  def create
    @mk_user = MkUser.new(mk_user_params)

    respond_to do |format|
      if @mk_user.save
        format.html { redirect_to @mk_user, notice: 'Mk user was successfully created.' }
        format.json { render :show, status: :created, location: @mk_user }
      else
        format.html { render :new }
        format.json { render json: @mk_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mk_users/1
  # PATCH/PUT /mk_users/1.json
  def update
    respond_to do |format|
      if @mk_user.update(mk_user_params)
        if @mk_user.mobile == true
          format.html { redirect_to mobile_marketcons_venedor_path(user_id: @mk_user.user_id), notice: 'Mk user was successfully updated.' }
        else
          format.html { redirect_to marketcons_venedor_path(user_id: @mk_user.user_id), notice: 'Mk user was successfully updated.' }
        end
        format.json { render :show, status: :ok, location: @mk_user }
      else
        format.html { render :edit }
        format.json { render json: @mk_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mk_users/1
  # DELETE /mk_users/1.json
  def destroy
    @mk_user.destroy
    respond_to do |format|
      format.html { redirect_to mk_users_url, notice: 'Mk user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mk_user
      @mk_user = MkUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mk_user_params
      params.require(:mk_user).permit(:user_id, :nom, :cognoms, :adreca, :codi_postal, :municipi, :email, :telefon, :web, :mostrar_adreca, :mostrar_email, :mostrar_telefon, :mostrar_web, :mk_image_user, :mobile)
    end
end

app/helpers/mk_users_helper.rb
module MkUsersHelper
end

app/views/mk_users/_form.html.erb
<%= simple_form_for(@mk_user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :nom %>
    <%= f.input :cognoms %>
    <%= f.input :adreca %>
    <%= f.input :codi_postal %>
    <%= f.input :municipi %>
    <%= f.input :email %>
    <%= f.input :telefon %>
    <%= f.input :web %>
    <%= f.input :mostrar_adreca %>
    <%= f.input :mostrar_email %>
    <%= f.input :mostrar_telefon %>
    <%= f.input :mostrar_web %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/mk_users/edit.html.erb
<h1>Editing Mk User</h1>

<%= render 'form', mk_user: @mk_user %>

<%= link_to 'Show', @mk_user %> |
<%= link_to 'Back', mk_users_path %>

app/views/mk_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mk Users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Nom</th>
      <th>Cognoms</th>
      <th>Adreca</th>
      <th>Codi postal</th>
      <th>Municipi</th>
      <th>Email</th>
      <th>Telefon</th>
      <th>Web</th>
      <th>Mostrar adreca</th>
      <th>Mostrar email</th>
      <th>Mostrar telefon</th>
      <th>Mostrar web</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mk_users.each do |mk_user| %>
      <tr>
        <td><%= mk_user.user_id %></td>
        <td><%= mk_user.nom %></td>
        <td><%= mk_user.cognoms %></td>
        <td><%= mk_user.adreca %></td>
        <td><%= mk_user.codi_postal %></td>
        <td><%= mk_user.municipi %></td>
        <td><%= mk_user.email %></td>
        <td><%= mk_user.telefon %></td>
        <td><%= mk_user.web %></td>
        <td><%= mk_user.mostrar_adreca %></td>
        <td><%= mk_user.mostrar_email %></td>
        <td><%= mk_user.mostrar_telefon %></td>
        <td><%= mk_user.mostrar_web %></td>
        <td><%= link_to 'Show', mk_user %></td>
        <td><%= link_to 'Edit', edit_mk_user_path(mk_user) %></td>
        <td><%= link_to 'Destroy', mk_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mk User', new_mk_user_path %>

app/views/mk_users/new.html.erb
<h1>New Mk User</h1>

<%= render 'form', mk_user: @mk_user %>

<%= link_to 'Back', mk_users_path %>

app/views/mk_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @mk_user.user_id %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @mk_user.nom %>
</p>

<p>
  <strong>Cognoms:</strong>
  <%= @mk_user.cognoms %>
</p>

<p>
  <strong>Adreca:</strong>
  <%= @mk_user.adreca %>
</p>

<p>
  <strong>Codi postal:</strong>
  <%= @mk_user.codi_postal %>
</p>

<p>
  <strong>Municipi:</strong>
  <%= @mk_user.municipi %>
</p>

<p>
  <strong>Email:</strong>
  <%= @mk_user.email %>
</p>

<p>
  <strong>Telefon:</strong>
  <%= @mk_user.telefon %>
</p>

<p>
  <strong>Web:</strong>
  <%= @mk_user.web %>
</p>

<p>
  <strong>Mostrar adreca:</strong>
  <%= @mk_user.mostrar_adreca %>
</p>

<p>
  <strong>Mostrar email:</strong>
  <%= @mk_user.mostrar_email %>
</p>

<p>
  <strong>Mostrar telefon:</strong>
  <%= @mk_user.mostrar_telefon %>
</p>

<p>
  <strong>Mostrar web:</strong>
  <%= @mk_user.mostrar_web %>
</p>

<%= link_to 'Edit', edit_mk_user_path(@mk_user) %> |
<%= link_to 'Back', mk_users_path %>