config/routes.rb
Rails.application.routes.draw do
  
  resources :epd_indicators
  resources :epds
  resources :mk_puntuacions
  resources :mk_imatges
  resources :mk_documents
  resources :mk_users
  get 'marketcons/index'
  get 'marketcons', to: 'marketcons#index', as: :marketcons
  get 'marketcons/about'
  get 'marketcons/producte'
  get 'marketcons/perfil'
  get 'marketcons/venedor'
  get 'marketcons/nou_anunci'
  get 'marketcons/editar_anunci'
  get 'marketcons/comprova_unitats_categoria'
  get 'marketcons/categoria'
  get 'marketcons/missatges'
  get 'marketcons/aprovacions'
  get 'marketcons/publicats'
  get 'marketcons/usuaris'
  get 'marketcons/reserva_producte'
  get 'marketcons/anula_reserva_producte'
  get 'marketcons/producte_venut'
  get 'marketcons/producte_amagar'

  get 'mobile_marketcons/index'
  get 'mobile_marketcons', to: redirect('mobile_marketcons/index?distancia=tots&preu=tots&categoria=tots'), as: :mobile_marketcons
  get 'mobile_marketcons/about'
  get 'mobile_marketcons/producte'
  get 'mobile_marketcons/perfil'
  get 'mobile_marketcons/venedor'
  get 'mobile_marketcons/puntua_usuari'
  get 'mobile_marketcons/grava_puntuacio_usuari'
  get 'mobile_marketcons/nou_anunci'
  get 'mobile_marketcons/editar_anunci'
  get 'mobile_marketcons/comprova_unitats_categoria'
  get 'mobile_marketcons/categoria'
  get 'mobile_marketcons/missatges'
  get 'mobile_marketcons/aprovacions'
  get 'mobile_marketcons/publicats'
  get 'mobile_marketcons/usuari'
  get 'mobile_marketcons/usuaris'
  get 'mobile_marketcons/reserva_producte'
  get 'mobile_marketcons/anula_reserva_producte'
  get 'mobile_marketcons/producte_venut'
  get 'mobile_marketcons/producte_amagar'
  get 'mobile_marketcons/idioma'

  get 'mk_products/aprovar'
  get 'mk_products/desaprovar'
  resources :mk_categories
  resources :mk_missatges
  resources :mk_products
  resources :document_dapcons
  resources :organitzacio_afiliades
  get 'cas_practics/llistat'
  resources :cas_practics
  resources :indicador_usuaris
  resources :producte_dapcons_usuaris
  resources :indicadors
  resources :tipus_dada_inventaris
  resources :tipus_indicadors
  resources :producte_dapcons
  get 'dapcons', to: 'dapcons#index', :as => :dapcons
  get 'dapcons/index'
  get 'dapcons/que_son'
  get 'dapcons/utilitat'
  get 'dapcons/organitzacions_afiliades'
  get 'dapcons/productes_registrats'
  get 'dapcons/empreses_dapcons'
  get 'dapcons/documents_oficials'
  get 'dapcons/administradors'
  get 'dapcons/consell_assessor'
  get 'dapcons/panells_sectorials'
  get 'dapcons/eco_platform'
  get 'dapcons/entitats_colaboradores'
  get 'dapcons/verificadors'
  get 'dapcons/afiliacio'
  get 'dapcons/registrar_producte'
  get 'dapcons/contacte'
  get 'dapcons/comparador'
  get 'dapcons/llistat_productes'
  resources :videos
  get 'noticies/llistat'
  resources :noticies
  resources :empreses
  resources :categories
  resources :categoria_productes
  resources :ecoetiqueta_productes
  resources :ecoetiquetes
  resources :document_productes
  resources :productes
  devise_for :users
  
  get 'temes_clau/index'
  get 'temes_clau/marc_conceptual'
  get 'temes_clau/materials'
  get 'temes_clau/energia_passius'
  get 'temes_clau/energia_actius'
  get 'temes_clau/energia_renovables'
  get 'temes_clau/aigua'
  get 'temes_clau/residus'
  get 'temes_clau/salut'
  get 'temes_clau/economia_circular'
  get 'temes_clau/infraestructura_verda'


  get 'cas_practics/:cas_practics_id/edit_ca', to: 'cas_practics#edit_ca', :as => :cas_practics_edit_ca
  get 'cas_practics/:cas_practics_id/edit_es', to: 'cas_practics#edit_es', :as => :cas_practics_edit_es
  get 'cas_practics/:cas_practics_id/edit_en', to: 'cas_practics#edit_en', :as => :cas_practics_edit_en


  get 'home/index'
  get 'home/panel'
  get 'home/quisom'
  get 'home/avislegal'
  get 'home/cookies'
  get 'home/contacta'
  get 'home/logout'

  get 'index.php/ca/sistema_dapc/*other', to: redirect('dapcons/index?locale=ca')
  get 'index.php/es/sistema_dapc/*other', to: redirect('dapcons/index?locale=es')
  get 'index.php/ca/*other', to: redirect('home/index?locale=ca')
  get 'index.php/es/*other', to: redirect('home/index?locale=es')

  get 'interaccions', to: 'interaccions#create', as: :interaccions
  get 'interaccions/descarregues_dapcons', to: 'interaccions#descarregues_dapcons'
  
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@noticies = Noticia.where(dapc: false).order('data').last(2)
  end

  def panel
  	@casos_practics = CasPractic.where(visible: false)
  end

  def logout
  	render layout: "mobile"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contacta.html.erb
<div class="container">
	<div class="grid-x grid-margin-x">
		<div class="medium-12 cell">
			
			<% if params[:locale] == 'ca' %>
				
				<div class="sub-title-container">
	        <span class="sub-title">Contacta</span>
	      </div>

	      <p>Per a qualsevol dubte, comentari o aclariment relacionat amb el web podeu escriure'ns a: sostenible@cateb.cat</p>

	    <% elsif params[:locale] == 'es' %>

	    	<div class="sub-title-container">
	        <span class="sub-title">Contacto</span>
	      </div>

	      <p>Para cualquier duda, comentario o aclaración en relación a la página web pueden escribirnos a: sostenible@cateb.cat</p>

	    <% else %>

	    	<div class="sub-title-container">
	        <span class="sub-title">Contact</span>
	      </div>

	      <p>For any doubt, comment or clarification related to the web you can write to us at: sostenible@cateb.cat</p>

	    <% end %>
	  </div>
	</div>
</div>

app/views/home/cookies.html.erb
<div class="container">
	<div class="grid-x grid-margin-x">
		<div class="medium-9 cell">
			
			<% if params[:locale] == 'ca' %>
				
				<div class="sub-title-container">
	        <span class="sub-title">Política de cookies</span>
	      </div>


<h4>1. Definició i funció de les cookies.</h4>

<p>Què són les cookies? Una cookie o galeta és un arxiu que es descarrega al seu ordinador en accedir a determinades pàgines web. Les cookies permeten a una pàgina web, entre altres coses, emmagatzemar i recuperar informació sobre els hàbits de navegació d'un usuari o del seu equip i, depenent de la informació que continguin i de la forma en què utilitzi el seu equip, es poden utilitzar per reconèixer l'usuari.</p>

<h4>2. Quins tipus de cookies utilitza aquesta pàgina web?</h4>

<p>Galetes tècniques i de personalització: necessàries o convenients per a la prestació de determinats serveis. Les primeres permeten a l'usuari la navegació a través de la pàgina web i la utilització dels diferents serveis que hi ha, i les segones permeten accedir a l'usuari al servei amb algunes característiques de caràcter general predefinides. S'utilitzen cookies per pel manteniment de sessió quan és necessari. Si es desactiven aquestes galetes es podria no rebre correctament els continguts del lloc web.</p>




<p>Cookies analítiques, ja sigui perque són tractades per nosaltres o per tercers, permeten fer el seguiment i anàlisi estadística del comportament del conjunt dels usuaris. Si es desactiven aquestes galetes, el lloc web podrà seguir funcionant, sense perjudici que la informació captada per aquestes cookies sobre l'ús del nostre web i sobre el seu contingut permet millorar els nostres serveis.</p>


<h4>3. Forma de desactivar o eliminar les cookies.</h4>

<p>Vostè pot permetre, bloquejar o eliminar les cookies instal.lades en el seu equip mitjançant la configuració de les opcions del navegador en el vostre ordinador.</p>
<ul>
	<li><a href="http://windows.microsoft.com/es-es/internet-explorer/delete-manage-cookies#ie=ie-11">Configuració per a Internet Explorer</li>
	<li><a href="https://support.mozilla.org/es/kb/Borrar%20cookies">Configuració per a Mozilla Firefox</a></li>
	<li><a href="https://support.google.com/chrome/answer/95647?hl=%22es%22">Configuració per a Google Chrome</a></li>
	<li><a href="http://support.apple.com/es-es/HT1677">Configuració per a Safari</a></li>
</ul>
<p>En cas que no accepti les cookies és possible que la pàgina web no funcioni correctament.</p>


<h4>4. Informació sobre la identificació de qui utilitza les cookies.</h4>

<p>La informació obtinguda per les cookies és tractada pel Col·legi de l’Arquitectura Tècnic de Barcelona (Cateb) com a gestor de la web en que s´ha contractat la prestació del servei d´analítica amb [.] on seguint el link podrà accedir a les seves condicions legals.</p>

</div>
</div>
</div>	


			<% else %>

				<div class="sub-title-container">
	        <span class="sub-title">Política de cookies</span>
	      </div>

	      <h4>1. Definición y función de las cookies. </h4>

<p>¿Qué son las cookies? Una cookie o galleta es un archivo que se descarga en su ordenador al acceder a determinadas páginas web. Las cookies permiten a una página web, entre otras cosas, almacenar y recuperar información sobre los hábitos de navegación de un usuario o de su equipo y, dependiendo de la información que contengan y de la forma en que utilice su equipo, se pueden utilizar para reconocer al usuario. </p>

<h4>2. ¿Qué tipos de cookies utiliza esta página web? </h4>

<p>Galletas técnicas y de personalización: necesarias o convenientes para la prestación de determinados servicios. Las primeras permiten al usuario la navegación a través de la página web y la utilización de los diferentes servicios que hay, y las segundas permiten acceder al usuario al servicio con algunas características de carácter general predefinidas. Se utilizan cookies para el mantenimiento de sesión cuando es necesario. Si se desactivan estas galletas se podría no recibir correctamente los contenidos del sitio web. </p>




<p>Cookies analíticas, ya sea porque son tratadas por nosotros o por terceros, permiten hacer el seguimiento y análisis estadístico del comportamiento del conjunto de los usuarios. Si se desactivan estas galletas, el sitio web podrá seguir funcionando, sin perjuicio de que la información captada por estas cookies sobre el uso de nuestra web y sobre su contenido permite mejorar nuestros servicios. </p>


<h4>3. Forma de desactivar o eliminar las cookies. </h4>

<p>Usted puede permitir, bloquear o eliminar las cookies instaladas en su equipo mediante la configuración de las opciones del navegador en su ordenador. </p>
<ul>
<li><a href="http://windows.microsoft.com/es-es/internet-explorer/delete-manage-cookies#ie=ie-11">Configuración para Internet Explorer </li>
<li><a href="https://support.mozilla.org/es/kb/Borrar%20cookies">Configuración para Mozilla Firefox </a></li>
<li><a href="https://support.google.com/chrome/answer/95647?hl=%22es%22">Configuración para Google Chrome </a></li>
<li><a href="http://support.apple.com/es-es/HT1677">Configuración para Safari </a></li>
</ul>
<p>En caso de que no acepte las cookies es posible que la página web no funcione correctamente. </p>


<h4>4. Información sobre la identificación de quien utiliza las cookies. </h4>

<p>La información obtenida por las cookies es tratada por el Colegio de la Arquitectura Técnica como gestor de la web en que se ha contratado la prestación del servicio de analítica con [.] donde siguiendo el link podrá acceder a sus condiciones legales. </p>

</div>
</div>
</div>

	    <% end %>
	  </div>
		<div class="medium-3 cell">
			
		</div>
	</div>
</div>

app/views/home/index.html.erb
<div class="hero">
	<div class="container">
		<div class="grid-x grid-margin-x">
			<div class="medium-6 cell">
				<div class="home-top-image-container">
          <% if params[:locale] == 'es' %>
						<%= link_to video_path(107) do %>
          		<%= image_tag('https://dcyqocdz7x3wj.cloudfront.net/imatges/Irve_ES_v2.jpg', :class => 'responsive-img') %>
          	<% end %>
          <% elsif params[:locale] == 'en' %>
          	<%= link_to video_path(107) do %>
          		<%= image_tag('https://dcyqocdz7x3wj.cloudfront.net/imatges/Irve_EN_v2.jpg', :class => 'responsive-img') %>
          	<% end %>
          <% else %>
          	<%= link_to video_path(107) do %>
          		<%= image_tag('https://dcyqocdz7x3wj.cloudfront.net/imatges/Irve_CA_v2.jpg', :class => 'responsive-img') %>
          	<% end %>
          <% end %>
		    </div>
			</div>
			<div class="medium-6 cell">
				<div class="home-top-image-container">
					<% if params[:locale] == 'es' %>
						<%= link_to video_path(108) do %>
          		<%= image_tag('https://dcyqocdz7x3wj.cloudfront.net/imatges/Reutilizacion_ES.jpg', :class => 'responsive-img') %>
          	<% end %>
          <% elsif params[:locale] == 'en' %>
          	<%= link_to video_path(108) do %>
          		<%= image_tag('https://dcyqocdz7x3wj.cloudfront.net/imatges/Reutilizacion_ES.jpg', :class => 'responsive-img') %>
          	<% end %>
          <% else %>
          	<%= link_to video_path(108) do %>
          		<%= image_tag('https://dcyqocdz7x3wj.cloudfront.net/imatges/Reutilizacion_ES.jpg', :class => 'responsive-img') %>
          	<% end %>
          <% end %>
		    </div>
			</div>
		</div>
	</div>
</div>


<div class="container">
	<div class="grid-x grid-margin-x">
		<div class="small-12 cell">
			<div class="divider">
			</div>
		</div>
	</div>
	<div class="grid-x grid-margin-x">
		<div class="medium-8 cell">
			<div class="titol-seccio">
				<%= t('.novetats_web') %>
			</div>
			<div class="grid-x grid-margin-x">
				<div class="medium-6 cell">
					<div class="card">
						<% if params[:locale] == 'es' %>
			        <div class="card-image">
			          <%= image_tag('https://dcyqocdz7x3wj.cloudfront.net/imatges/comparador_es.png', :class => 'responsive-img') %>
			        </div>
			        <div class="card-section">
			          <p>Presentamos una nueva herramienta, el comparador de productos DAPcons<sup>®</sup>. Las Declaraciones Ambientales de Producto nos proporcionan diferentes indicadores ambientales de los productos, como el potencial de calentamiento global o de formación de ozono fotoquímico.</p>
								<p>Gracias al comparador podéis valorar mejor las diferencias entre los diferentes productos DAPcons<sup>®</sup> y la herramienta también os permite introducir información de nuevos productos para hacer comparaciones.</p>
			          <div class="card-action">
		              <%= link_to "Ir al comparador", dapcons_comparador_path %>
		            </div>
			        </div>
			      <% elsif params[:locale] == 'en' %>
			      	<div class="card-image">
			          <%= image_tag('https://dcyqocdz7x3wj.cloudfront.net/imatges/comparador_en.png', :class => 'responsive-img') %>
			        </div>
			        <div class="card-section">
			          <p>We present a new tool, the DAPcons<sup>®</sup> product comparator. Environmental Product Declarations provide us different environmental indicators of products, such as the potential for global warming or photochemical ozone formation.</p>
								<p>Thanks to the comparator you can better assess the differences between the different DAPcons<sup>®</sup> products. The tool also allows you to enter information about new products to make comparisons.</p>
			          <div class="card-action">
		              <%= link_to "Go to comparator", dapcons_comparador_path %>
		            </div>
			        </div>
			      <% else %>
			      	<div class="card-image">
			          <%= image_tag('https://dcyqocdz7x3wj.cloudfront.net/imatges/comparador_dapcons2.png', :class => 'responsive-img') %>
			        </div>
			        <div class="card-section">
			          <p>Presentem una nova eina, el comparador de productes DAPcons<sup>®</sup>. Les Declaracions Ambientals de Producte ens proporcionen diferents indicadors ambientals dels productes, com el potencial d'escalfament global o de formació d'ozó fotoquímic.</p>
			          <p>Gràcies al comparador podeu valorar millor les diferències entre els diferents productes DAPcons<sup>®</sup> i l'eina també us permet introduir informació de nous productes per a fer comparacions.</p>
			          <div class="card-action">
		              <%= link_to "Anar al comparador", dapcons_comparador_path %>
		            </div>
			        </div>
			      <% end %>
		      </div>
				</div>
				<div class="medium-6 cell">
					<div class="card">
						<% if params[:locale] == 'es' %>
			        <div class="card-image">
			          <%= image_tag('https://dcyqocdz7x3wj.cloudfront.net/imatges/casos_es.png', :class => 'responsive-img') %>
			        </div>
			        <div class="card-section">
			          <p>Ahora puedes publicar tus propios casos prácticos en la web para dar a conocer los proyectos más destacados desde el punto de vista ambiental. Si el edificio destaca por estar construido con materiales de bajo impacto ambiental, o tiene un consumo de energía muy bajo, o utiliza soluciones innovadoras en general, seguro que a la comunidad le interesa conocerlo.</p>
								<p>Una vez hayas introducido la información del proyecto nosotros lo valoraremos y lo publicaremos en la web para que pueda acceder todo el mundo.</p>
			          <div class="card-action">
		              <%= link_to "Publica tu primer proyecto", producte_dapcons_usuaris_path %>
		            </div>
			        </div>
			      <% elsif params[:locale] == 'en' %>
			      	<div class="card-image">
			          <%= image_tag('https://dcyqocdz7x3wj.cloudfront.net/imatges/casos_en.png', :class => 'responsive-img') %>
			        </div>
			        <div class="card-section">
			          <p>Now you can publish your own case studies on the web in order to publicize the most outstanding projects from an environmental point of view. If the building stands out because it is built with materials with low environmental impact, or has a very low power consumption, or uses innovative solutions in general, surely the community is interested in knowing it.</p>
								<p>Once you have entered the information on the project, we will evaluate it and publish it on the web so that it can be accessed by everyone.</p>
			          <div class="card-action">
		              <%= link_to "Publish your first project", producte_dapcons_usuaris_path %>
		            </div>
			        </div>
			      <% else %>
			      	<div class="card-image">
			          <%= image_tag('https://dcyqocdz7x3wj.cloudfront.net/imatges/casos_practics2.png', :class => 'responsive-img') %>
			        </div>
			        <div class="card-section">
			          <p>Ara pots publicar els teus propis casos pràctics al web per tal de donar a conèixer els projectes més destacats des del punt de vista ambiental. Si l'edifici destaca per estar construit amb materials de baix impacte ambiental, o té un consum d'energia molt baix, o utilitza solucions innovadores en general, segur que a la comunitat li interessa conèixer-lo. </p>
			          <p>Una vegada hagis introduït la informació del projecte nosaltres el valorarem i el publicarem al web per a que hi pugui accedir tothom.</p>
			          <div class="card-action">
		              <%= link_to "Publica el teu primer projecte", producte_dapcons_usuaris_path %>
		            </div>
			        </div>
			      <% end %>
		      </div>
				</div>
			</div>
		</div>
		<div class="medium-4 cell">
			<div class="titol-seccio">
				<%= t('.newsletter') %>
			</div>
			<% if params[:locale] == 'ca' %>
				<a href="https://www3.apabcn.cat/l/618811/2019-01-29/5jtr6">
					<div class="newsletter-container">
	          <span class="newsletter-titol"><%= t('.subscriu_newsletter') %></span>
	          <p><span class="newsletter-text"><%= t('.text_newsletter') %></span></p>
		      </div>
		    </a>
		  <% else %>
		  	<a href="https://www3.apabcn.cat/l/618811/2019-01-29/5jtr2">
					<div class="newsletter-container">
	          <span class="newsletter-titol"><%= t('.subscriu_newsletter') %></span>
	          <p><span class="newsletter-text"><%= t('.text_newsletter') %></span></p>
		      </div>
		    </a>
		  <% end %>
		
		
		

		
			<div class="spacer"></div>
			<div class="titol-seccio">
				<%= t('.noticies') %>
			</div>
			<div class="noticies-container">
        <% @noticies.each do |noticia| %>
          <%= link_to noticia do %>
	          <div class="noticia-lateral-container">
	            <% if noticia.imatge_noticia.attached? %>
	              <%= image_tag noticia.imatge_noticia %>
	            <% end %>
	            <h3 class="noticia-lateral-titol">
	              <% if params[:locale] == 'en' %>
	                <%= noticia.titol_en %>
	              <% elsif params[:locale] == 'es' %>
	                <%= noticia.titol_es %>
	              <% else %>
	                <%= noticia.titol_ca %>
	              <% end %>
	            </h3>
	          </div>
	        <% end %>
        <% end %>
      </div>

		</div>
	</div>
</div>

app/views/home/logout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Log out</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  .dialog {
    margin-top: 60px;
    text-align: center;
  }
  </style>
</head>

<body class="rails-default-error-page">
  <div class="dialog">
    <div>
      <p><%= t('.sessio_finalitzada') %></p>
    </div>
  </div>
</body>

<script>
  $(document).ready(function() {
    if (navigator.userAgent.indexOf('gonative') > -1) {
      setTimeout(function() {
        window.location.href = "https://www.csostenible.net/mobile_marketcons/index?distancia=tots&preu=tots&categoria=tots&locale=ca"; 
      }, 500);
    }
    else {
      window.location.href = 'https://www.csostenible.net/home/index?locale=ca';
    }
  });
</script>
</html>

app/views/home/panel.html.erb
<div class="container">
  <div class="grid-x grid-margin-x">
    <div class="medium-12 cell">
      <div class="main-title-container">
        <span class="main-title"><%= t('.panell') %></span>
      </div>
    </div>
  </div>

  <div class="grid-x grid-margin-x">
    <% if current_user.role == 'editor' %>
      <div class="medium-4 large-3 cell">
        <%= link_to noticies_llistat_path do %>
          <div class="panell-control-item">
            <%= image_tag("https://dcyqocdz7x3wj.cloudfront.net/imatges/reunio_verificadors_1.jpg", class: 'imatge-item-panell-control') %>
            <div class="text-item-panell-control">
              <h3 class="panell-control-item-title"><%= t('.noticies') %></h3>
              <p><%= t('.text_noticies') %></p>
            </div> 
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="medium-4 large-3 cell">
      <%= link_to new_producte_path do %>
        <div class="panell-control-item">
          <%= image_tag("https://dcyqocdz7x3wj.cloudfront.net/imatges/producte_fusta.jpg", class: 'imatge-item-panell-control') %>
          <div class="text-item-panell-control">
            <h3 class="panell-control-item-title"><%= t('.productes') %></h3>
            <% if current_user.role == 'editor' %>
              <p><%= t('.text_1_productes') %></p>
            <% else %>
              <p><%= t('.text_2_productes') %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="medium-4 large-3 cell">
      <%= link_to cas_practics_llistat_path do %>
        <div class="panell-control-item">
          <%= image_tag("https://dcyqocdz7x3wj.cloudfront.net/imatges/cas12_max_2.jpg", class: 'imatge-item-panell-control') %>
          <div class="text-item-panell-control">
            <h3 class="panell-control-item-title"><%= t('.casos_practics') %></h3>
            <% if current_user.role == 'editor' %>
              <p><%= t('.text_1_casos_practics') %></p>
            <% else %>
              <p><%= t('.text_1_casos_practics') %></p>
            <% end %>
          </div>
        </div>
      <% end %>  
    </div>
    <div class="medium-4 large-3 cell">
      <% if current_user.role == 'editor' %>
        <%= link_to producte_dapcons_index_path do %>
          <div class="panell-control-item">
            <%= image_tag("https://dcyqocdz7x3wj.cloudfront.net/imatges/taula_dades3.jpg", class: 'imatge-item-panell-control') %>
            <div class="text-item-panell-control">
              <h3 class="panell-control-item-title"><%= t('.declaracions') %></h3>
              <p><%= t('.text_declaracions_editor') %></p>
            </div>
          </div>
        <% end %>
      <% else %>
        <%= link_to producte_dapcons_usuaris_path do %>
          <div class="panell-control-item">
            <%= image_tag("https://dcyqocdz7x3wj.cloudfront.net/imatges/taula_dades3.jpg", class: 'imatge-item-panell-control') %>
            <div class="text-item-panell-control">
              <h3 class="panell-control-item-title"><%= t('.declaracions') %></h3>
              <p><%= t('.text_declaracions_usuari') %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if current_user.role == 'editor' %>
    <div class="grid-x grid-margin-x">
      <div class="medium-4 large-3 cell">
        <%= link_to interaccions_descarregues_dapcons_path do %>
          <div class="panell-control-item">
            <%= image_tag("https://dcyqocdz7x3wj.cloudfront.net/imatges/taula_descarregues.jpg", class: 'imatge-item-panell-control') %>
            <div class="text-item-panell-control">
              <h3 class="panell-control-item-title"><%= t('.descarregues') %></h3>
              <p><%= t('.text_descarregues') %></p>
            </div>
          </div>
        <% end %>
      </div>
      <div class="medium-4 large-3 cell">
        <%= link_to marketcons_aprovacions_path do %>
          <div class="panell-control-item">
            <%= image_tag("https://dcyqocdz7x3wj.cloudfront.net/imatges/imatge_marketcons.jpg", class: 'imatge-item-panell-control') %>
            <div class="text-item-panell-control">
              <h3 class="panell-control-item-title"><%= t('.marketcons') %></h3>
              <p><%= t('.text_marketcons') %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <% if @casos_practics.count > 0 %>
      <div class="grid-x grid-margin-x">
        <div class="medium-12 cell">
          <div class="callout alert">
            <%= t('.continguts_pendents_moderacio') %>
          </div>
        </div>
        <div class="medium-12 cell">
          <div class="container-continguts-pendents-moderacio">
            <span class="text-destacat"><%= t('.casos_practics') %>:</span> 
            <% if @casos_practics.count == 1 %>
              <%= link_to t('.un_cas_pendent'), cas_practics_llistat_path %>
            <% else %>
              <%= t('.hi_ha') %> <%= @casos_practics.count %> <%= link_to t('.casos_pendents'), cas_practics_llistat_path %>
            <% end %>
          </div>
      </div>
    <% end %>
  <% end %>

  <% if current_user.role == 'empresa_dapcons' %>
    <div class="grid-x grid-margin-x">
      <div class="medium-4 large-3 cell">
        <%= link_to interaccions_descarregues_dapcons_path do %>
          <div class="panell-control-item">
            <%= image_tag("https://dcyqocdz7x3wj.cloudfront.net/imatges/taula_descarregues.jpg", class: 'imatge-item-panell-control') %>
            <div class="text-item-panell-control">
              <h3 class="panell-control-item-title"><%= t('.descarregues') %></h3>
              <p><%= t('.text_descarregues') %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>