config/routes.rb
Rails.application.routes.draw do
  
  resources :epd_indicators
  resources :epds
  resources :mk_puntuacions
  resources :mk_imatges
  resources :mk_documents
  resources :mk_users
  get 'marketcons/index'
  get 'marketcons', to: 'marketcons#index', as: :marketcons
  get 'marketcons/about'
  get 'marketcons/producte'
  get 'marketcons/perfil'
  get 'marketcons/venedor'
  get 'marketcons/nou_anunci'
  get 'marketcons/editar_anunci'
  get 'marketcons/comprova_unitats_categoria'
  get 'marketcons/categoria'
  get 'marketcons/missatges'
  get 'marketcons/aprovacions'
  get 'marketcons/publicats'
  get 'marketcons/usuaris'
  get 'marketcons/reserva_producte'
  get 'marketcons/anula_reserva_producte'
  get 'marketcons/producte_venut'
  get 'marketcons/producte_amagar'

  get 'mobile_marketcons/index'
  get 'mobile_marketcons', to: redirect('mobile_marketcons/index?distancia=tots&preu=tots&categoria=tots'), as: :mobile_marketcons
  get 'mobile_marketcons/about'
  get 'mobile_marketcons/producte'
  get 'mobile_marketcons/perfil'
  get 'mobile_marketcons/venedor'
  get 'mobile_marketcons/puntua_usuari'
  get 'mobile_marketcons/grava_puntuacio_usuari'
  get 'mobile_marketcons/nou_anunci'
  get 'mobile_marketcons/editar_anunci'
  get 'mobile_marketcons/comprova_unitats_categoria'
  get 'mobile_marketcons/categoria'
  get 'mobile_marketcons/missatges'
  get 'mobile_marketcons/aprovacions'
  get 'mobile_marketcons/publicats'
  get 'mobile_marketcons/usuari'
  get 'mobile_marketcons/usuaris'
  get 'mobile_marketcons/reserva_producte'
  get 'mobile_marketcons/anula_reserva_producte'
  get 'mobile_marketcons/producte_venut'
  get 'mobile_marketcons/producte_amagar'
  get 'mobile_marketcons/idioma'

  get 'mk_products/aprovar'
  get 'mk_products/desaprovar'
  resources :mk_categories
  resources :mk_missatges
  resources :mk_products
  resources :document_dapcons
  resources :organitzacio_afiliades
  get 'cas_practics/llistat'
  resources :cas_practics
  resources :indicador_usuaris
  resources :producte_dapcons_usuaris
  resources :indicadors
  resources :tipus_dada_inventaris
  resources :tipus_indicadors
  resources :producte_dapcons
  get 'dapcons', to: 'dapcons#index', :as => :dapcons
  get 'dapcons/index'
  get 'dapcons/que_son'
  get 'dapcons/utilitat'
  get 'dapcons/organitzacions_afiliades'
  get 'dapcons/productes_registrats'
  get 'dapcons/empreses_dapcons'
  get 'dapcons/documents_oficials'
  get 'dapcons/administradors'
  get 'dapcons/consell_assessor'
  get 'dapcons/panells_sectorials'
  get 'dapcons/eco_platform'
  get 'dapcons/entitats_colaboradores'
  get 'dapcons/verificadors'
  get 'dapcons/afiliacio'
  get 'dapcons/registrar_producte'
  get 'dapcons/contacte'
  get 'dapcons/comparador'
  get 'dapcons/llistat_productes'
  resources :videos
  get 'noticies/llistat'
  resources :noticies
  resources :empreses
  resources :categories
  resources :categoria_productes
  resources :ecoetiqueta_productes
  resources :ecoetiquetes
  resources :document_productes
  resources :productes
  devise_for :users
  
  get 'temes_clau/index'
  get 'temes_clau/marc_conceptual'
  get 'temes_clau/materials'
  get 'temes_clau/energia_passius'
  get 'temes_clau/energia_actius'
  get 'temes_clau/energia_renovables'
  get 'temes_clau/aigua'
  get 'temes_clau/residus'
  get 'temes_clau/salut'
  get 'temes_clau/economia_circular'
  get 'temes_clau/infraestructura_verda'


  get 'cas_practics/:cas_practics_id/edit_ca', to: 'cas_practics#edit_ca', :as => :cas_practics_edit_ca
  get 'cas_practics/:cas_practics_id/edit_es', to: 'cas_practics#edit_es', :as => :cas_practics_edit_es
  get 'cas_practics/:cas_practics_id/edit_en', to: 'cas_practics#edit_en', :as => :cas_practics_edit_en


  get 'home/index'
  get 'home/panel'
  get 'home/quisom'
  get 'home/avislegal'
  get 'home/cookies'
  get 'home/contacta'
  get 'home/logout'

  get 'index.php/ca/sistema_dapc/*other', to: redirect('dapcons/index?locale=ca')
  get 'index.php/es/sistema_dapc/*other', to: redirect('dapcons/index?locale=es')
  get 'index.php/ca/*other', to: redirect('home/index?locale=ca')
  get 'index.php/es/*other', to: redirect('home/index?locale=es')

  get 'interaccions', to: 'interaccions#create', as: :interaccions
  get 'interaccions/descarregues_dapcons', to: 'interaccions#descarregues_dapcons'
  
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mk_product.rb
class MkProduct < ApplicationRecord

	belongs_to :user
	has_many :mk_documents, dependent: :destroy, inverse_of: :mk_product
	accepts_nested_attributes_for :mk_documents, allow_destroy: true, reject_if: ->(attrs) { attrs['nom'].blank? }
	has_many :mk_imatges, dependent: :destroy, inverse_of: :mk_product
	accepts_nested_attributes_for :mk_imatges, allow_destroy: true

end

app/controllers/mk_products_controller.rb
class MkProductsController < ApplicationController
  before_action :set_mk_product, only: [:show, :edit, :update, :destroy]

  # GET /mk_products
  # GET /mk_products.json
  def index
    @mk_products = MkProduct.all
  end

  # GET /mk_products/1
  # GET /mk_products/1.json
  def show
  end

  # GET /mk_products/new
  def new
    @mk_product = MkProduct.new
  end

  # GET /mk_products/1/edit
  def edit
  end

  # POST /mk_products
  # POST /mk_products.json
  def create
    @mk_product = MkProduct.new(mk_product_params)

    respond_to do |format|
      if @mk_product.save
        if @mk_product.mobile == true
          format.html { redirect_to mobile_marketcons_producte_path(mk_product_id: @mk_product.id), notice: 'Mk product was successfully created.' }
        else
          format.html { redirect_to marketcons_producte_path(mk_product_id: @mk_product.id), notice: 'Mk product was successfully created.' }
        end 
        format.json { render :show, status: :created, location: @mk_product }
      else
        if @mk_product.mobile == true
          format.html { redirect_to mobile_marketcons_nou_anunci_path }
        else
          format.html { redirect_to marketcons_nou_anunci_path }
        end 
        format.json { render json: @mk_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mk_products/1
  # PATCH/PUT /mk_products/1.json
  def update
    respond_to do |format|
      if @mk_product.update(mk_product_params)
        if @mk_product.mobile == true
          format.html { redirect_to mobile_marketcons_producte_path(mk_product_id: @mk_product.id), notice: 'Mk product was successfully updated.' }
        else
          format.html { redirect_to marketcons_producte_path(mk_product_id: @mk_product.id), notice: 'Mk product was successfully updated.' }
        end
        format.json { render :show, status: :ok, location: @mk_product }
      else
        format.html { render :edit }
        format.json { render json: @mk_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mk_products/1
  # DELETE /mk_products/1.json
  def destroy
    @mk_product.destroy
    respond_to do |format|
      if current_user.role == 'editor'
        format.html { redirect_to marketcons_aprovacions_path, notice: 'Mk product was successfully destroyed.' }
      else
        format.html { redirect_to marketcons_venedor_path(user_id: current_user.id), notice: 'Mk product was successfully destroyed.' }
      end
      format.json { head :no_content }
    end
  end

  def aprovar
    producte = MkProduct.find(params[:mk_product_id])
    producte.aprovat = true
    producte.save
    redirect_to marketcons_aprovacions_path
  end

  def desaprovar
    producte = MkProduct.find(params[:mk_product_id])
    producte.aprovat = false
    producte.save
    redirect_to marketcons_publicats_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mk_product
      @mk_product = MkProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mk_product_params
      params.require(:mk_product).permit(
        :user_id, 
        :nom, 
        :descripcio, 
        :categoria, 
        :adreca, 
        :codi_postal, 
        :municipi, 
        :latitud, 
        :longitud, 
        :preu, 
        :visible, 
        :venut, 
        :aprovat, 
        :pes, 
        :unitats, 
        :enviament, 
        :adreca_oculta,  
        :reservat, 
        :reservat_usuari, 
        :mobile, 
        mk_documents_attributes: [:id, :user_id, :mk_product_id, :nom, :document, :_destroy],
        mk_imatges_attributes: [:id, :user_id, :mk_product_id, :descripcio, :mk_product_imatge, :_destroy])
    end
end

app/helpers/mk_products_helper.rb
module MkProductsHelper
end

app/views/mk_products/_form.html.erb
      <%= simple_form_for(@mk_product) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <br/>
          <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
          <%= f.input :aprovat, as: :hidden, input_html: { value: true } %>
          <%= f.input :visible, as: :hidden, input_html: { value: true } %>
          <%= f.input :mobile, as: :hidden, input_html: { value: false } %>
          <%= f.input :latitud, as: :hidden %>
          <%= f.input :longitud, as: :hidden %>

          <div class="grid-x grid-margin-x">
            <div class="medium-6 cell">
              <%= f.input :nom %>
              <% if params[:locale] == 'es' %>
                <%= f.input :categoria, collection: @categories, label_method: :nom_es, value_method: :id, unitats_method: :unitats, include_blank: false, selected: @mk_product.categoria %>
              <% elsif params[:locale] == 'en' %>
                <%= f.input :categoria, collection: @categories, label_method: :nom_en, value_method: :id, unitats_method: :unitats, include_blank: false, selected: @mk_product.categoria %>
              <% else %>
                <%= f.input :categoria, collection: @categories, label_method: :nom_ca, value_method: :id, unitats_method: :unitats, include_blank: false, selected: @mk_product.categoria %>
              <% end %>
            </div>
            <div class="medium-6 cell">
              <%= f.input :descripcio, input_html: {rows: 4} %>
            </div>
          </div>
          <div class="grid-x grid-margin-x">
            <div class="medium-2 small-4 cell">
              <%= f.input :preu %>
            </div>
            <div class="medium-1 small-2 cell">
              <div class="mk-text-ressaltat">€</div>
            </div>
            <div class="medium-2 small-4 cell">
              <div id="container-pes">
                <%= f.input :pes %>
              </div>
              <div id="container-unitats">
                <%= f.input :unitats %>
              </div>
            </div>
            <div class="medium-1 small-2 cell">
              <div class="mk-text-ressaltat" id="text-kg">kg</div>
            </div>
            <div class="medium-6 cell">
              <%= f.input :enviament, collection: [[t('.comprador_buscar'), 'comprador_buscar'], [t('.venedor_porta'), 'venedor_porta'], [t('.a_negociar'), 'negociar']] %>
            </div>
          </div>
          <div class="grid-x grid-margin-x">
            <div class="medium-6 cell">
              <%= f.input :adreca %>
            </div>
            <div class="medium-2 cell">
              <%= f.input :codi_postal %>
            </div>
            <div class="medium-4 cell">
              <%= f.input :municipi %>
            </div>
          </div>
          <div class="grid-x grid-margin-x">
            <div class="medium-12 cell">
              <%= f.input :adreca_oculta %>
              <br/>
            </div>
          </div>

          <div class="grid-x grid-margin-x">
            <div class="medium-12 cell">
              <div class="mk-documents-container">
                <%= t('.adjuntar_documents') %>
                <%= f.simple_fields_for :mk_documents do |mk_document| %>
                  <%= render 'mk_document_fields', f: mk_document %>
                <% end %>
                <div class="links">
                  <%= link_to_add_association t('.afegeix_document'), f, :mk_documents, html_options = {class: "mk-afegir-document button"} %>
                </div>
              </div>
            </div>
          </div>

          <div class="grid-x grid-margin-x">
            <div class="medium-12 cell">
              <div class="mk-imatges-container">
                <%= t('.adjuntar_imatges') %>
                <%= f.simple_fields_for :mk_imatges do |mk_imatge| %>
                  <%= render 'mk_imatge_fields', f: mk_imatge %>
                <% end %>
                <div class="links">
                  <%= link_to_add_association t('.afegeix_imatge'), f, :mk_imatges, html_options = {class: "mk-afegir-imatge button"} %>
                </div>
              </div>
            </div>
          </div>

          <br/>
        </div>

        <div class="form-actions">
          <div class="grid-x grid-margin-x">
            <div class="medium-2 cell">
              <%= f.button :submit, t('.guardar') %>
            </div>
            <div class="medium-6 cell">
              <span class="mk-text-discret"><%= t('.anuncis_revisio') %></span>
            </div>
          </div>
        </div>
      <% end %>

<script>
$(function() {
  $("#container-unitats").hide();
  getLocation();
});


$("#mk_product_categoria").change(function() {
  $.ajax({
    type: 'GET',
    url: '<%= marketcons_comprova_unitats_categoria_path %>',
    data: {
      categoria_id: $("#mk_product_categoria").val()
    },
    success: function(data) {
      if(data == 'unitats'){
        $("#container-pes").hide();
        $("#text-kg").hide();
        $("#container-unitats").show();

      } 
      if(data == 'kg') {
        $("#container-pes").show();
        $("#text-kg").show();
        $("#container-unitats").hide();
      }
    }
  });
});

function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(recordPosition);
  } else {
    x.innerHTML = "Aquest navegador no suporta la geolocalització";
  }
}

function recordPosition(position) {
  $("#mk_product_latitud").val(position.coords.latitude);
  $("#mk_product_longitud").val(position.coords.longitude);
};

</script>

app/views/mk_products/_mk_document_fields.html.erb
<div class="nested-fields">
	<div class="grid-x grid-margin-x">
		<div class="medium-6 cell">
			<%= f.input :nom %>
		</div>
		<div class="medium-1 cell">
			<div class="eliminar-document">
				<%= link_to_remove_association "Eliminar", f %>
			</div>
		</div>
	</div>
</div>

app/views/mk_products/_mk_imatge_fields.html.erb
<div class="nested-fields">
	<div class="grid-x grid-margin-x">
		<div class="medium-6 cell">
			<%= f.input :descripcio %>
		</div>
		<div class="medium-1 cell">
			<div class="eliminar-document">
				<%= link_to_remove_association "Eliminar", f %>
			</div>
		</div>
	</div>
</div>

app/views/mk_products/edit.html.erb
<h1>Editing Mk Product</h1>

<%= render 'form', mk_product: @mk_product %>

<%= link_to 'Show', @mk_product %> |
<%= link_to 'Back', mk_products_path %>

app/views/mk_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mk Products</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Nom</th>
      <th>Descripcio</th>
      <th>Categoria</th>
      <th>Adreca</th>
      <th>Codi postal</th>
      <th>Municipi</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th>Preu</th>
      <th>Visible</th>
      <th>Venut</th>
      <th>Aprovat</th>
      <th>Pes</th>
      <th>Unitats</th>
      <th>Enviament</th>
      <th>Adreca oculta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mk_products.each do |mk_product| %>
      <tr>
        <td><%= mk_product.user_id %></td>
        <td><%= mk_product.nom %></td>
        <td><%= mk_product.descripcio %></td>
        <td><%= mk_product.categoria %></td>
        <td><%= mk_product.adreca %></td>
        <td><%= mk_product.codi_postal %></td>
        <td><%= mk_product.municipi %></td>
        <td><%= mk_product.latitud %></td>
        <td><%= mk_product.longitud %></td>
        <td><%= mk_product.preu %></td>
        <td><%= mk_product.visible %></td>
        <td><%= mk_product.venut %></td>
        <td><%= mk_product.aprovat %></td>
        <td><%= mk_product.pes %></td>
        <td><%= mk_product.unitats %></td>
        <td><%= mk_product.enviament %></td>
        <td><%= mk_product.adreca_oculta %></td>
        <td><%= link_to 'Show', mk_product %></td>
        <td><%= link_to 'Edit', edit_mk_product_path(mk_product) %></td>
        <td><%= link_to 'Destroy', mk_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mk Product', new_mk_product_path %>

app/views/mk_products/new.html.erb
<h1>New Mk Product</h1>

<%= render 'form', mk_product: @mk_product %>

<%= link_to 'Back', mk_products_path %>

app/views/mk_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @mk_product.user_id %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @mk_product.nom %>
</p>

<p>
  <strong>Descripcio:</strong>
  <%= @mk_product.descripcio %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @mk_product.categoria %>
</p>

<p>
  <strong>Adreca:</strong>
  <%= @mk_product.adreca %>
</p>

<p>
  <strong>Codi postal:</strong>
  <%= @mk_product.codi_postal %>
</p>

<p>
  <strong>Municipi:</strong>
  <%= @mk_product.municipi %>
</p>

<p>
  <strong>Latitud:</strong>
  <%= @mk_product.latitud %>
</p>

<p>
  <strong>Longitud:</strong>
  <%= @mk_product.longitud %>
</p>

<p>
  <strong>Preu:</strong>
  <%= @mk_product.preu %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @mk_product.visible %>
</p>

<p>
  <strong>Venut:</strong>
  <%= @mk_product.venut %>
</p>

<p>
  <strong>Aprovat:</strong>
  <%= @mk_product.aprovat %>
</p>

<p>
  <strong>Pes:</strong>
  <%= @mk_product.pes %>
</p>

<p>
  <strong>Unitats:</strong>
  <%= @mk_product.unitats %>
</p>

<p>
  <strong>Enviament:</strong>
  <%= @mk_product.enviament %>
</p>

<p>
  <strong>Adreca oculta:</strong>
  <%= @mk_product.adreca_oculta %>
</p>

<%= link_to 'Edit', edit_mk_product_path(@mk_product) %> |
<%= link_to 'Back', mk_products_path %>